= Part I - Hacking preparations

include::../attributes.adoc[]

OWASP Juice Shop offers multiple ways to be deployed and used. The
author himself has seen it run on

* restricted corporate Windows machines
* heavily customized Linux distros
* all kinds of Apple hardware
* overclocked Windows gaming notebooks
* Chromebooks with native Linux support
* various cloud platforms

Chance is pretty high that you will be able to get it running on your
computer as well. This part of the book will help your install and run
the Juice Shop as well as guide you through the application and some
fundamental rules and hints for hacking it.

Should you run into issues during installation or launch of the
application, please do not hesitate to
https://gitter.im/bkimminich/juice-shop[ask for help in the community chat]
or by
https://github.com/juice-shop/juice-shop/issues[opening a GitHub issue]!
Please just make sure that you flipped through
xref:appendix/troubleshooting.adoc#_troubleshooting[the appendix on troubleshooting] first.