= Broken Access Control

include::../attributes.adoc[]

____
Most computer systems are designed for use with multiple users.
Privileges mean what a user is permitted to do. Common privileges
include viewing and editing files, or modifying system files.

Privilege escalation means a user receives privileges they are not
entitled to. These privileges can be used to delete files, view
private information, or install unwanted programs such as viruses. It
usually occurs when a system has a bug that allows security to be
bypassed or, alternatively, has flawed design assumptions about how it
will be used. Privilege escalation occurs in two forms:

* Vertical privilege escalation, also known as _privilege elevation_,
where a lower privilege user or application accesses functions or
content reserved for higher privilege users or applications (e.g.
Internet Banking users can access site administrative functions or
the password for a smartphone can be bypassed.)
* Horizontal privilege escalation, where a normal user accesses
functions or content reserved for other normal users (e.g. Internet
Banking User A accesses the Internet bank account of User B)footnote:3_1_1[https://en.wikipedia.org/wiki/Privilege_escalation]
____

[discrete]
== Challenges covered in this chapter

|===
| Name | Description | Difficulty

| Admin Section
| Access the administration section of the store.
| ⭐⭐

| CSRF
| Change the name of a user by performing Cross-Site Request Forgery from another origin.
| ⭐⭐⭐

| Easter Egg
| Find the hidden easter egg.
| ⭐⭐⭐⭐

| Five-Star Feedback
| Get rid of all 5-star customer feedback.
| ⭐⭐

| Forged Feedback
| Post some feedback in another user's name.
| ⭐⭐⭐

| Forged Review
| Post a product review as another user or edit any user's existing review.
| ⭐⭐⭐

| Manipulate Basket
| Put an additional product into another user's shopping basket.
| ⭐⭐⭐

| Product Tampering
| Change the `href` of the link within the OWASP SSL Advanced Forensic Tool (O-Saft) product description into _https://owasp.slack.com_.
| ⭐⭐⭐

| SSRF
| Request a hidden resource on server through server.
| ⭐⭐⭐⭐⭐⭐

| View Basket
| View another user's shopping basket.
| ⭐⭐

| Web3 Sandbox
| Find an accidentally deployed code sandbox for writing smart contracts on the fly.
| ⭐
|===

== Access the administration section of the store

Just like the score board, the admin section was not part of your "happy
path" tour because there seems to be no link to that section either. In
case you were already
xref:part2/injection.adoc#_log_in_with_the_administrators_user_account[logged in with the administrator account]
you might have noticed that not even for him there is a corresponding
option available in the main menu.

include::partial$hints/adminSectionChallenge.adoc[]

== Change the name of a user by performing Cross-Site Request Forgery from another origin

This challenge requires you to craft the code for the Cross-Site
Request Forgery (CSRF) attack within http://htmledit.squarefree.com,
which represents another
https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy[origin]
than the Juice Shop. You can enter your HTML and Script code in the
upper half of the page, while the result is instantly displayed in the
lower half.

include::partial$hints/csrfChallenge.adoc[]

_Please also be aware that the challenge is designed to be solved only with
the specified online HTML editor. This means that Juice Shop will not
recognize the challenge as solved when you are using another origin,
such as for example JSFiddle or CodePen._

== ⚠️ Important information about browser compatibility

There is an ongoing initiative, called "Incrementally Better
Cookies", which aims to reduce the impact of CSRF attacks by changing
the default cookie handling of browsers. It is strongly recommended to
understand these changes before attempting this challenge, as otherwise
it might not be solvable:

* An overview of the planned changes to `SameSite` can be found in https://web.dev/samesite-cookie-recipes/.
* At the time of this writing, the challenge should work fine with Firefox 96.x or older.
* If you are in doubt, you can check the behavior of your browser using
the website https://samesite-sandbox.glitch.me/ - if you see the text
"set ❌" in the first row below the column "Cross-site?", your browser
uses the old default and should be able to solve the challenge.
* Although Chrome can be temporarily switched back to the old behavior by starting
it with the option `--disable-features=SameSiteByDefaultCookies`, the CSRF attack will probably not execute anymore in Chrome 80.x or newer.

== Find the hidden easter egg

____
An Easter egg is an intentional inside joke, hidden message, or
feature in an interactive work such as a computer program, video game
or DVD menu screen. The name is used to evoke the idea of a
traditional Easter egg hunt.footnote:3_1_2[https://en.wikipedia.org/wiki/Easter_egg_(media)]
____

include::partial$hints/easterEggLevelOneChallenge.adoc[]

_When you open the easter egg file, you might be a little disappointed,
as the developers taunt you about not having found *the real* easter
egg! Of course finding *that* is
xref:part2/cryptographic-issues.adoc#_apply_some_advanced_cryptanalysis_to_find_the_real_easter_egg[a follow-up challenge]
to this one._

== Get rid of all 5-star customer feedback

If you successfully solved above
<<_access_the_administration_section_of_the_store,admin section challenge>>
deleting the 5-star feedback is very easy.

include::partial$hints/feedbackChallenge.adoc[]

== Post some feedback in another user's name

The Juice Shop allows users to provide general feedback including a star
rating and some free text comment. When logged in, the feedback will be
associated with the current user. When not logged in, the feedback will
be posted anonymously. This challenge is about vilifying another user by
posting a (most likely negative) feedback in his or her name!

include::partial$hints/forgedFeedbackChallenge.adoc[]

== Post a product review as another user or edit any user's existing review

The Juice Shop allows users to provide reviews of all the products. A
user has to be logged in before they can post any review for any of the
products. This challenge is about vilifying another user by posting a
(most likely bad) review in his or her name!

include::partial$hints/forgedReviewChallenge.adoc[]

== Put an additional product into another user's shopping basket

<<_view_another_users_shopping_basket,View another user's shopping basket>>
was only about spying out other customers. For this challenge you need
to get your hands dirty by putting a product into someone else's basket
that cannot be already in there!

include::partial$hints/basketManipulateChallenge.adoc[]

== Change the href of the link within the O-Saft product description

The _OWASP SSL Advanced Forensic Tool (O-Saft)_ product has a link in
its description that leads to that projects wiki page. In this challenge
you are supposed to change that link so that it will send you to
http://kimminich.de instead. It is important to exactly follow the
challenge instruction to make it light up green on the score board:

include::partial$hints/changeProductChallenge.adoc[]

== Request a hidden resource on server through server

This Server-side Request Forgery challenge will come back to the malware
you used in
xref:part2/injection.adoc#_infect_the_server_with_juicy_malware_by_abusing_arbitrary_command_execution[Infect the server with juicy malware by abusing arbitrary command execution].

include::partial$hints/ssrfChallenge.adoc[]

____
In a Server-Side Request Forgery (SSRF) attack, the attacker can abuse
functionality on the server to read or update internal resources. The
attacker can supply or a modify a URL which the code running on the
server will read or submit data to, and by carefully selecting the
URLs, the attacker may be able to read server configuration such as
AWS metadata, connect to internal services like http enabled databases
or perform post requests towards internal services which are not
intended to be exposed. footnote:3_1_3[https://owasp.org/www-community/attacks/Server_Side_Request_Forgery]
____

== View another user's shopping basket

This horizontal privilege escalation challenge demands you to access the
shopping basket of another user. Being able to do so would give an
attacker the opportunity to spy on the victims shopping behaviour. He
could also play a prank on the victim by manipulating the items or their
quantity, hoping this will go unnoticed during checkout. This could lead
to some arguments between the victim and the vendor.

include::partial$hints/basketAccessChallenge.adoc[]

== Find an accidentally deployed code sandbox

include::partial$hints/web3SandboxChallenge.adoc[]
