= Finding the Score Board[[_finding_the_score_board]]

include::../attributes.adoc[]

In part 1 you were introduced to the Score Board and learned how it
tracks your challenge hacking progress. You also had a "happy path" tour
through the Juice Shop application from the perspective of a regular
customer without malicious intentions. But you never saw the Score
Board, did you?

[discrete]
== Challenges covered in this chapter

|===
| Name | Description | Difficulty

| Score Board
| Find the carefully hidden 'Score Board' page.
| ⭐
|===

== Find the carefully hidden 'Score Board' page

Why was the Score Board not visited during the "happy path" tour?
Because there seemed to be no link anywhere in the application that
would lead you there! You know that it must exist, which leaves two
possible explanations:

. You missed the link during the initial mapping of the application
. There is a URL that leads to the Score Board but it is not
hyperlinked to

* Knowing it exists, you can simply _guess_ what URL the Score Board
might have.
* Alternatively, you can try to find a reference or clue within the
parts of the application that are _not usually visible_ in the browser
